### ISSUE TITLE
Use a logical order for city list

### ISSUE THREAD

**Issue by danblaker** [BrandNewCongress/DEPRECATED-website#113]
Visit http://brandnewcongress.org/tour on a mobile device. Note that the list of states appears to be in a completely arbitrary order: NC, CA, IL, etc. 

Assuming the intent is for visitors to quickly find their state and take action to RSVP, the list should be in alphabetical order by state.

**Comment by saikat** [comment]
Would love a PR for this.  Though maybe what we need to do is think up a good UI for the general purpose event map.  I'm currently thinking of doing something very similar to map.berniesanders.com.
