### ISSUE TITLE
Expats - Please make it possible for expats to sign up

### ISSUE THREAD

**Issue by toponymie** [BrandNewCongress/DEPRECATED-website#126]
without falsifying their info. I am an American living in France, there are thousands of American citizens overseas who are politically active and interested. Please change your sign up requirements so that we don't have to provide false US phone numbers and addresses. I could of course give you any number of US addresses where I don't live but then you'd be sending me info relative to activities in the false zipcode I provided and that would be a waste of space and time for all.

**Comment by saikat** [comment]
This is a great point, and we should fix this.  Marking as status-approved.

**Comment by toponymie** [comment]
Thank you!
