### ISSUE TITLE
API to connect Google form to Nation Builder

### ISSUE THREAD

**Issue by haleyzink** [BrandNewCongress/DEPRECATED-website#127]
For a fluid host experience we are currently using a google form, over the form in NB. This causes a necessity to hand enter in form data into Nationbuilder, and also does not allow for the autosend Nationbuilder event confirmation. 
- [ ] Use API to connect this form [Be a BNC Livestream Host](https://docs.google.com/forms/d/e/1FAIpQLSdIwq5XF1eznEgYAArFARKZjBkaBpnQD9n7a61GvoWDCHS-Ag/viewform) to the nation builder [Sept 20th Livestream Events](https://brandnewcongress.nationbuilder.com/admin/sites/1/pages/193/events) page
- [ ] Make sure that the information enters in all proper fields, then ends up on map, and that hosts will get confirmation emails

**Comment by saikat** [comment]
If there is dev time to work on this, I'd maybe suggest instead using that to move the full host signup form to be an on-map experience so there isn't a separate google form at all.
