### ISSUE TITLE
Use link instead of button for Contribute header link

### ISSUE THREAD

**Issue by cyranix** [BrandNewCongress/DEPRECATED-website#128]
Currently, the nav header built in this repo has its markup copied into the main layout template for NationBuilder-hosted pages. However, the functionality of the Contribute link — opening an ActBlue page in a new tab — is part of the React code, so the button does nothing on NB-hosted pages.

We need to redo [this section](https://github.com/BrandNewCongress/website/blob/master/src/components/Navigation.jsx#L245-L253) of the navigation to use a link with `target="_blank"` and appropriate button-like styling, so it's still a highly visible call to action while also being more portable for NB-hosted pages.

**Comment by cyranix** [comment]
@saikat The alternative here would be to use two separate React mounts — one for the header and one for the main page content — and then we'd be able to webpack the header JS separately and upload that to NB. But unless there are plans for making the header more interactive, that seems like overkill for a static nav header.

**Comment by saikat** [comment]
The NB version of the code is a copy and paste of the code from the site, right?  I may be misunderstanding how it works.  In that case, I think we probably don't need to change anything about how the code in the actual BNC website works and just change it on the NB side?

**Comment by cyranix** [comment]
That's also an option. We would just have to remember to redo that change if there's ever a change to the header that we'd sync to NB — and "just have to remember" is a phrase that sets off little alarm bells in my head. 😉 I would prefer to have something easily repeatable, but you can make the call.
