### ISSUE TITLE
Add a nationbuilder tag to new signups on the website

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#136]
When a new person signs up on brandnewcongress.org, they should get tagged in Nationbuilder with the `signup-nb` tag.  The place to do this is probably right after the signup call in `server/index.js` in the `app.post('/signup'` route.

**Comment by TristanShepherd** [comment]
Don't you need the person's ID to tag them in the NB API, and isn't that created in NB after the post request? This might be better solved by doing daily bulk tagging!

**Comment by TristanShepherd** [comment]
Alternatively, you can create a filter for new signups in NB and then apply a tag to that on a regular basis.....

**Comment by TristanShepherd** [comment]
I'm not going to throw this into git, but you just need to add this below to JSON object "person" in "requestBody" (it's on line 50 of sever/index.js) :

tags: [
"signup-nb"
]
