### ISSUE TITLE
Make a better looking page for our plan

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#142]
Some design would be nice wouldn't it. Also buttons and stuff.

**Comment by roberthouse54** [comment]
Here is just a design concept. (Did this pretty fast, at work, etc). Basically:

1. Make the copy shorter and punchier.
2. Put a video front and center.
3. More direct and actionable and fun calls-to-action

![bnc1](https://cloud.githubusercontent.com/assets/20047260/21509202/cd5e1ba0-cc54-11e6-8369-a8bf384c2df5.png)
