### ISSUE TITLE
Zip codes not making it into Nationbuilder

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#144]

**Comment by andrewbredow** [comment]
I'm looking for a place to help out and am planning to take a look at this issue this weekend. Any gut ideas as to what's going on here? At first glance, it looks like the API call to Nationbuilder is formatted correctly.

**Comment by andrewbredow** [comment]
I've tested the flow from the Signup widget on the homepage and it seems the data is ending up in nationbuilder where expected:

<img width="753" alt="screen shot 2016-11-13 at 8 38 01 am" src="https://cloud.githubusercontent.com/assets/96793/20246055/b0e41290-a97c-11e6-86de-16e0a7ce4f9e.png">

Is there another form somewhere that is also supposed to be posting data to Nationbuilder?

**Comment by andrewbredow** [comment]
Oh! It appears this may have been recently fixed in e8c0145. This issue can probably be resolved.
