### ISSUE TITLE
Suggest deleting duplicate paragraphs on FAQ page

### ISSUE THREAD

**Issue by bkelly33** [BrandNewCongress/DEPRECATED-website#153]
Two different questions on this page ("Are you really talking about running Republicans" etc. and "So why will conservatives support this") contain the same two (consecutive) paragraphs (the first one starts with "Brand New Congress is not bi-partisan or non-partisan, we're 'post-partisan"; the second with "The irony is that". I understand that some readers will pick and choose questions and thus maybe not notice the duplicatoin, but for those who read all the way through, the repetition could be  disorienting ("Didn't I just read this? Did I lose my place?") and is certainly unnecessary.

**Comment by saikat** [comment]
Good point -- yeah we were thinking that a bit of repetition on the FAQ is better than not as most people would probably not read it through and we want to make sure the main points are understood.  Having said that I'll give it a second look to see if we can at least make it not so repetitive :).

**Comment by bkelly33** [comment]
In my experience, it's o.k. to say less than you think is important in the trust that truly motivated and curious readers will eventually fill in the blanks themselves. It shows respect for their ability and patience for their learning process. If I'm too anxious to give them everything at once, they may feel that they're being "force-fed" and recoil accordingly. But it is a balance that can be hard to strike in individual cases. I would hope that no one is going to pop in and just read one FAQ and its answer. I suspect a lot of browsing will go on.
