### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by techsoldaten** [BrandNewCongress/DEPRECATED-website#177]
Getting the following error install npm packages on a fresh checkout:

    npm ERR! peerinvalid The package react-dom@15.3.2 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer material-ui@0.15.4 wants react-dom@^15.0.0
    npm ERR! peerinvalid Peer react-look@1.0.1 wants react-dom@^0.14.3 || ^15.0.0
   npm ERR! peerinvalid Peer react-addons-test-utils@15.4.1 wants react-dom@^15.4.1

Material UI asks for specific versions of react-dom that don't match what's in package.json. /me thinks package.json should have material-ui version >= 0.15 instead, to get around this.

Thoughts?

**Comment by saikat** [comment]
Hm, that could make sense.  Can you try that and see if it fixes the issue?
