### ISSUE TITLE
Make brandnewcongress.org/work

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#83]
This is going to be the central organizing portal centered around our goal to hit 100k supporters in every congressional district.  I'm imagining /work looks like this: https://gomockingbird.com/projects/n24027s/XIqXhT

For organize locally, the info we need is largely on https://docs.google.com/document/d/1Op0OaZNuykCJckSCn4vABDEr4VEdTrMeTsPCZFNSJo4/edit

Once we finish this we should change all links to /teams to instead point to /work.  This means both in the website and informing help desk/call team/orientation team/speakers team/comms teams about the change.

**Comment by camgaertner** [comment]
Here's my mobile mockup we talked about.
![untitled-4](https://cloud.githubusercontent.com/assets/10566658/16569279/30941354-41fa-11e6-81ac-d7d67ad98ae7.png)

**Comment by saikat** [comment]
For a v1 one, I think the goals here should be:

1. Set up static information in a central area, combining our current /work and /teams pages.
1. Get a good user flow going

**Comment by saikat** [comment]
Combine this with #143 -- we need to refocus this page on nominations.
