### ISSUE TITLE
Set up a stylesheet for our email templates

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#84]

**Comment by blcarson** [comment]
I can take this one if nobody else has jumped on it yet. We also need to switch out the link to the reddit logo in the footer as the subreddit it's linking to is getting shut down.

**Comment by blcarson** [comment]
Yeah it looks like they're planning on closing it after the convention:

https://www.reddit.com/r/SandersForPresident/comments/4uq5cs/state_of_the_subreddit_address_and_the_future_of/

Is there a reason you've got the button pointing there rather then /r/brandnewcongress?

Building out something responsive for Nationbuilder wont be a problem. I requested an invite for progcode - if we can get someone to approve that I'll hop on and get details.

**Comment by saikat** [comment]
Hm strange -- the button should actually be pointing to /r/brandnewcongress.

**Comment by saikat** [comment]
(I thought that was the subreddit you were talking about)

**Comment by blcarson** [comment]
Oh ok, that makes more sense :) Will put that on the list to fix.

**Comment by blcarson** [comment]
The reddit icon on the footer is pointing here:

http://go.brandnewcongress.org/r?u=http%3A%2F%2Fwww.reddit.com%2Fsubmit%3Furl%3Dhttp%3A%2F%2Fbrandnewcongress.org%26title%3DBrand%2BNew%2BCongress&e=560929562c4e316af39d7a612418b068&utm_source=brandnewcongress&utm_medium=email&utm_campaign=after_roll_call&n=5

But is redirecting here because the link has already been submitted:

https://www.reddit.com/r/SandersForPresident/comments/4hysip/brand_new_congress/?submit_url=http%3A%2F%2Fbrandnewcongress.org&already_submitted=true&submit_title=Brand+New+Congress

Should probably just make that link point to /r/brandnewcongress

**Comment by saikat** [comment]
@blcarson So I think the footer links got fixed.  But as for an email stylesheet, could you start by creating a mockup or design of what you'd like it to look like?  I think it can stay really simple (like the Bernie emails) and don't even want to put our logo at the top or anything.  For the footer, I want to keep the social buttons and I'd actually like to add 4 kinds of opt-outs.  This is extending this project a bit -- we could have those four opt-outs listed in the e-mail footer or have the unsubscribe link go to a page where the options are presented.  What I'd like to do are these options:

Choose your supporter level and we'll tailor e-mails accordingly:
1) Full supporter. We'll send you all our e-mails and make sure you know everything is going on.
2) Time giver. We'll send you all our e-mails except for e-mails where we ask for money. We understand if you can't give money for a variety of reasons. We'll still let you know how to get involved and help with your time.
3) Curious but not all-in. We'll send you at most 2 e-mails a month just keeping you updated on what we're doing and how things are going, but won't ask you for time or money.
4) Voter only. We'll only contact you when we want to let you know who to vote for and when we want to remind you to go vote.

**Comment by cyranix** [comment]
@saikat — is customizing the degree of contact a high-priority issue? If so, can we can spin that off into a separate issue? Let's close this out unless we have other email stylesheet work to do.
