### ISSUE TITLE
Create an events portal / map

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/DEPRECATED-website#98]
Things we need (this is updated from comments below, so if you don't have time to read through all the comments, you can just look at this).
- [ ] Make a map with the same UI as https://map.berniesanders.com but with, for now, one event type (Sept 20th Livestream)
- [ ] Have different colored dots for events of different sizes and types (Under 20 ppl, Over 20 ppl, Official event, College event)
- [ ] Have the "Host an Event" button go to a page with resources for how to host an event. These can just be online versions of what exists in brandnewcongress.org/work
  - [ ] Suggestions for layout on https://gomockingbird.com/projects/5tcim6p/4gXVnC
- [ ] Let people create events
- [ ] Let people RSVP for events
- [ ] Add a link to the map from the homepage
- [ ] make it more zoom in friendly (the dots stay the same size when zooming in, they don't get smaller)
- [ ] zoom the actual map out, as right now CA has cut off event titles
- [ ] make a link for the events down below the map, and have that separated out by state. 
- [ ] Add the ability to search by zip code, state or city for an event

I'm currently thinking that the map should be a new standalone app instead of being a part of the website.  This would also mean making a brandnewcongress-starter-kit that has the common resources (themes, navbar, etc.) that we could use between website and the new app. I will likely use https://github.com/saikat/react-apollo-starter-kit as the starting point.

**Comment by haleyzink** [comment]
Yes! Here our my notes: 
- [ ] automate "thanks for hosting" emails that direct to hosting guides 
- [ ] make it so people can edit even if they didn't set up event, perhaps make a credential step.
- [ ] Color code based on which state has less or more events
- Resources for hosts I am working on, trying to decide if we want this all on one page ( /volevents ) or on a specific two pages, one for event ( /get-together ) and one for map ( /ourhouses ) 
- Names of / are not nailed down

**Comment by saikat** [comment]
From @haleyzink in another issue:

- [ ] Create /<sept event name> and have it be hidden/ unlisted to be ready for launch
  - [ ] Nail down / name
  - [ ] Have the site work for pre event, event, and post event so it would have all the materials we are building for pre event (host resources/ party favours etc). it would be able to house the video for during (unless this isn't a good idea?). and then have the candidate nomination form, candidate litmus test, and vol litmus test

**Comment by haleyzink** [comment]
Can we also use different symbols for the different sizes of events? As in the docs saying where events are. College events would have one color, events under 20 would have one, and then large events would have another. Local established groups (BNC official backed) would get stars.

**Comment by haleyzink** [comment]
And what is time frame on this kind of job? thanks!

**Comment by saikat** [comment]
Checking with Rapi/Jon Culver on when/if we may be able to use the map
they've been working on, and then should have a better idea.

**Comment by rapicastillo** [comment]
Targeting to get it done by this weekend. API has been set, and done I believe.

**Comment by saikat** [comment]
Ok sweet -- so @haleyzink, my guess would be a week after that to have
something up on the site and with the RSVP flow we want and all that jazz.
Would that be a reasonable timeframe?

**Comment by haleyzink** [comment]
This weekend is great @rapicastillo thank you! 
 Yes, or sooner. @saikat The reason I asked is I'm laying out time frame for launch via email and socials. I am thinking earlier in August if possible, that way we have a little over a month for building up RSVPs. 
Thank you both!!

**Comment by saikat** [comment]
That makes sense -- just got word from Jon that we may have something
usable sooner than this weekend, so that would give me this weekend to try
to get stuff running.

**Comment by haleyzink** [comment]
That's awesome! Thanks @saikat  
I also already have some content basics. If that helps at all? If so I can post here or forward to you.

**Comment by saikat** [comment]
Yes that does help. Feel free to make some google docs or mockups (I made a
mockup tool a while back at https://gomockingbird.com/ to quickly draw
stuff out online) and post links here.  That way if other devs want to help
out they can also jump in.  Thanks Haley!

**Comment by haleyzink** [comment]
Here's a mock up concept. Obviously visuals would be better- but this is the basics of what to be there. Will keep editing and adding stuff. https://gomockingbird.com/projects/5tcim6p/4gXVnC

**Comment by haleyzink** [comment]
@rapicastillo how is the site going? Thanks so much for doing this!!

**Comment by haleyzink** [comment]
would it also be a possibility to put a countdown to the big event somewhere? Maybe on the homepage for this? @saikat

**Comment by saikat** [comment]
Countdown sounds like a good idea.

**Comment by haleyzink** [comment]
Updated To Do List: 

- [ ] Make an events page for the upcoming Sept 20th event. 

- [ ]  Map of the events that lets people create and sign up for events (ok if it sends them off to Nationbuilder map for it).

- [ ] Space on events page where hosting resources will be listed.

- [ ] Space on events page talking about Sept 20th watch party event

- [ ]  Prominent link from homepage

Here's a potential layout for site and information. https://gomockingbird.com/projects/5tcim6p/4gXVnC
Main concerns are simply getting it live and having it have ability to add events.

**Comment by cyranix** [comment]
Updated status:

* Built a short-term version hosted on NB for the 08/22 deadline.
* Will rebuild it better in this repo later this week.

Path is `/livestream` — we still need to discuss how we want to link to this page from the homepage.
